# Generated by Django 5.2.6 on 2025-10-06 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_carousel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
