# Generated by Django 5.2.6 on 2025-10-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_play_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='status',
            field=models.IntegerField(choices=[(1, 'Распроданы'), (2, 'Свободно')], default=2),
        ),
    ]
